# docker-compose.yml

version: '3'

services:
  app:
    container_name: "goserver"
    image: 'golang:1.6-onbuild'
    ports:
      - "3000:3000"
    links:
      - redis
    volumes:
      - "./src:/go/src/app"
    command: go run server.go
  
  redis:
    image: redis
