# docker-compose.yml

version: '3'

services:
  app:
    container_name: "goserver_web"
    build: .docker/app
    # image: 'golang:1.7'
    ports:
      - "3000:3000"
    links:
      - redis
    volumes:
      - ".:/go/src/app"
    command: go run /go/src/app/src/server.go
  
  redis:
    image: redis
